apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  type: LoadBalancer # for expose as loadbalancer
  # type: NodePort # for expose as nodeport
  ports:
  - port: 8090
    targetPort: http
    # nodePort: 30163 #30000-32767 # uncomment if NodePort used
    protocol: TCP
    name: http-svc